#pragma once

#define MAP_BG "image/map.png"
#define ROLL_BUTTON "image/roll button.png"
#define PLAY_BUTTON "image/play button.png"
#define ABOUT_BUTTON "image/about button.png"
#define BACK_BUTTON "image/back button.png"
#define DICE_ONE "image/one.png"
#define DCIE_TWO "image/two.png"
#define DCIE_THREE "image/three.png"
#define DCIE_FOUR "image/four.png"
#define DCIE_FIVE "image/five.png"
#define DCIE_SIX "image/six.png"
#define PION_HIJAU "image/hijau.png"
#define PION_MERAH "image/merah.png"
#define PION_KUNING "image/kuning.png"
#define PION_BIRU "image/biru.png"
#define MAIN_MENU_BG "image/main menu bg.png"
#define MAIN_MENU_BG "image/about bg.png"
#define MAIN_MENU_BG "image/tutorial bg.png"
#define MAIN_MENU_BG "image/game bg.png"
#define FONT "font/Embryotic.ttf"