#pragma once

#define MAP_BG "image/map2.png"
#define ROLL_BUTTON "image/roll button.png"
#define PLAY_BUTTON "image/play button.png"
#define ABOUT_BUTTON "image/about button.png"
#define TUTORIAL_BUTTON "image/tutorial button.png"
#define BACK_BUTTON "image/back button.png"
#define NEXT_BUTTON "image/next button.png"
#define PREV_BUTTON "image/prev button.png"
#define QUIT_BUTTON "image/quit button.png"
#define DICE_ONE "image/one.png"
#define DICE_TWO "image/two.png"
#define DICE_THREE "image/three.png"
#define DICE_FOUR "image/four.png"
#define DICE_FIVE "image/five.png"
#define DICE_SIX "image/six.png"
#define PION_HIJAU "image/hijau.png"
#define PION_MERAH "image/merah.png"
#define PION_KUNING "image/kuning.png"
#define PION_BIRU "image/biru.png"
#define MAIN_MENU_BG "image/main menu bg.png"
#define ABOUT_BG "image/about bg.png"
#define TUTORIAL1_BG "image/tutorial1 bg.png"
#define TUTORIAL2_BG "image/tutorial2 bg.png"
#define GAME_BG "image/game bg.png"
#define FONT "font/Embryotic.ttf"
#define FONT2 "font/SeasideResortNF.ttf"
#define MUSIC "music/ludo_music.wav"

#define WIDTH 1100
#define HEIGHT 750